cluster.name: "elasticsearch"
node.name: "elasticsearch"
network.host: 0.0.0.0

http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "Authorization"

#xpack.security.enabled: false
#xpack.monitoring.enabled: false
#xpack.watcher.enabled: false
#xpack.ml.enabled: false
